services:
  swisscom-portfolio:
    build: .
    container_name: "web-swisscom-portfolio"
    restart: always
    networks:
      - traefik_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`elyesghazel.ch`)"
      - "traefik.http.routers.portfolio.entrypoints=https"
      - "traefik.http.routers.portfolio.tls=true"
      - "traefik.http.routers.portfolio.tls.certresolver=cloudflare"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"

networks:
  traefik_proxy:
    external: true
